// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3jHUDJ4In-3t6zFAAGoLx14fQV-w6mOM',
    appId: '1:786001383731:web:a1c09d39e7658fd6ef2e46',
    messagingSenderId: '786001383731',
    projectId: 'fasum-4e89b',
    authDomain: 'fasum-4e89b.firebaseapp.com',
    storageBucket: 'fasum-4e89b.appspot.com',
    measurementId: 'G-D94E2Y7Y2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUsrSauNmjnuIbCiR3ebUyF6wWNd64XQ',
    appId: '1:786001383731:android:d3d5101f8330c72eef2e46',
    messagingSenderId: '786001383731',
    projectId: 'fasum-4e89b',
    storageBucket: 'fasum-4e89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsSIAN9FT6KavWQORs26cDOTfWpOGS80',
    appId: '1:786001383731:ios:136aaa661dec9f4aef2e46',
    messagingSenderId: '786001383731',
    projectId: 'fasum-4e89b',
    storageBucket: 'fasum-4e89b.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwsSIAN9FT6KavWQORs26cDOTfWpOGS80',
    appId: '1:786001383731:ios:3c6c67c0a856d268ef2e46',
    messagingSenderId: '786001383731',
    projectId: 'fasum-4e89b',
    storageBucket: 'fasum-4e89b.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
